### ISSUE TITLE
Styles für Whistles bitte anpassen

### ISSUE THREAD

**Issue by SimonAlm** [medizinmedien/cc-p-medonline-at#3]
@hostz-frank oder @wozo

ich weiß nicht wer das macht, bitte jedenefalls wie hier zu sehen die Styles der meditabs-horizontale-unterstrichene https://p.medonline.at/video-test-mit-whistle/

für die Seite so anpassen, dass die Titeln die gleiche blaue Farbe wie auf der Seite haben und die Highlight-Balken in dem Dunkelblau wie im Logo (produkt)

![p_med](https://cloud.githubusercontent.com/assets/8351449/6144680/7ad3bcf0-b1da-11e4-98ec-224b5eeb8db4.jpg)

**Comment by wozo** [comment]
hab es im headway css geändert...
passt's so?

**Comment by SimonAlm** [comment]
Danke, ja passt.

LG Simon
